ID: 0
cuda: false
env.id: Pendulum-v0
network.recurrent: false
network.hidden_size:
- 32
es.popsize: 128
es.mu0: 0.0
es.std0: 0.5
train.num_iteration: 1000
train.N: 5
train.T: 300
log.interval: 100
log.dir: logs
