ID: 0
cuda: false
env.id: CartPole-v1
network.recurrent: false
network.hidden_size:
- 32
es.algo: OpenAIES
es.popsize: 16
es.mu0: 0.0
es.std0: 0.5
train.num_iteration: 1000
train.N: 5
log.print_interval: 100
log.dir: logs
